# whitelist
branches:
  only:
    - gh-pages

before_install:
  - mkdir $HOME/pandoc
  - curl -O https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
  - unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc -d $HOME/pandoc
  - chmod +x $HOME/pandoc/pandoc
  - rm pandoc-1.12.3.zip
  - export PATH="$HOME/pandoc:$PATH"
  - pandoc --version
  - mkdir wkhtmltopdf
  - wget http://download.gna.org/wkhtmltopdf/0.12/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
  - tar --xz -xvf wkhtmltox-0.12.3_linux-generic-amd64.tar.xz -C wkhtmltopdf
  - export PATH=$PATH:${PWD}/wkhtmltopdf/wkhtmltox/bin/
  - pwd
  - ls -al ${PWD}/wkhtmltopdf/wkhtmltox/bin/
  - chmod u+x ./travis/build.sh
  - chmod u+x ./travis/publish.sh
  - export GIT_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
  - "export GIT_MODIFIED_FILES=\"$(git log --name-only --pretty=format: gh-pages -n 1)\""
  - echo "$GIT_MODIFIED_FILES" | grep 'tuto/tuto.md'; export TUTO_PUBLISH_PDF=$?; true

script: "./travis/build.sh"

after_success:
  - if [ $TUTO_PUBLISH_PDF -eq 0 ]; then ./travis/publish.sh; fi

env:
  global:
    - GH_USER_NAME=flyingeek
    - GH_PROJECT_NAME=editolido
    - GIT_AUTHOR_NAME=Travis
    - GIT_AUTHOR_EMAIL=noreply@travis-ci.org
    - RESULT_PDF_PATH=${TRAVIS_BUILD_DIR}/tuto/tuto.pdf
    - TZ="Europe/Paris"
    - secure: qnsPBztJpvxyvDDuxiteF+nwX2wffq5ZJgqlkzly8CHTCVgplbfdNzw5nH1fi0h8+2Hwt7LzAwycH/obZyIUA64UuEkZkCdJr/UhsLKGme2e9dgeaZ/M9N06XPJ6MJezRnflGssWOM/R8YWUiuvrOhc9JtVBISLzKRkxCK+bA8eTT9+6/HGUk4RxbDJITu5e8F8oUL+axHmOOvqjQ71JZDc6z+Qu+fWcnBUj7uWenT/nkTD7CigIM6kTX4tMPaUJcEm3TzZpPoQV0YXcS0ucSzVrTUYOCGkpuCgrbs8sKVopqsd/58EsIXxwoIRr6jeVX0uaqSZVjWqq8YFoZ6rldjI9AFr8sse45jZGBp+Z4Z1pFQ+ZwmjZEZSzOi05rcBhM452k1jG8PBNgA95CCWD+GlcEGe4ZcQLXcWNQDOKe7Phpsa0+uarj238HSwe1mbqc1pAkwCu3F4awYdFTtiN5t+OkVYvSMc6ncAP8affH2WKv1BqVQ5pX76//elmW2X0bl4eDvh2sD1BgB3HdjtrqXtd6OO5gfeLOpx5DTOfagSm0TaU7/IVfwT0OzpDeLS/10YhOaaQ38fK19ljTdlcD1KkO5TK72ZGkp5wczWofMRTQrSs6x+0eR/nILaocRL6rnV//HdQQ4eMdvoJy2wCbpUM6iQp9AC0L1k8QRvH4/k=
